# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: shortcode.dev
# email: your-email@example.com
description:  Cheatsheet lists HTML, CSS, Javascript elements, attributes and selectors.  
baseurl: "" # the subpath of your site, e.g. /blog
url: https://shortcode.dev # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: shortcode
# github_username:  shortcode

# Permalink style 
# Options: https://jekyllrb.com/docs/permalinks/#builtinpermalinkstyles
# permalink: none

host: shortcode

# Build settings
markdown: kramdown
# theme: minima
plugins:
  # - jekyll-feed

highlighter: rouge

sass:
  sass_dir: ./_styles
  style: compressed

theme-colour: '#202943'

collections_dir: _collections
collections:
  html:
    output: false
    permalink: html-cheatsheet
    icon: fab fa-html5
  css:
    output: false
    permalink: css-cheatsheet
    icon: fab fa-css3-alt
  javascript:
    output: false
    permalink: javascript-cheatsheet
    icon: fab fa-js-square
  liquid:
    output: false
    permalink: liquid-cheatsheet
    icon: fas fa-flask
  git:
    output: false
    permalink: git-cheatsheet
    icon: fab fa-github
  vue:
    output: false
    permalink: vue-cheatsheet
    icon: fab fa-vuejs
  node:
    output: false
    permalink: node-cheatsheet
    icon: fab fa-node-js

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
